/**
 * Textos de UI en español, centralizados (docs/03 · RNF-10).
 * Cuando llegue la internacionalización, este módulo se sustituye por
 * un framework de traducciones sin tocar los componentes.
 */
export const texts = {
  app: {
    name: "Planify",
    tagline: "Planifica tus ideas de proyecto",
    description: "Planifica tus ideas de proyecto con notas y diagramas.",
  },
  common: {
    unexpectedError: "Ha ocurrido un error inesperado. Inténtalo de nuevo.",
    tooManyAttempts:
      "Demasiados intentos seguidos. Espera un minuto e inténtalo de nuevo.",
    cancel: "Cancelar",
    save: "Guardar",
    rename: "Renombrar",
    delete: "Eliminar",
    actions: "Acciones",
    loading: "Cargando…",
    typeToConfirm: (value: string) => `Escribe «${value}» para confirmar`,
  },
  auth: {
    login: {
      title: "Entrar en Planify",
      subtitle: "Continúa donde lo dejaste.",
      email: "Email",
      password: "Contraseña",
      submit: "Entrar",
      noAccount: "¿No tienes cuenta?",
      createAccount: "Crea una",
    },
    register: {
      title: "Crear cuenta",
      subtitle: "Empieza a planificar tus ideas.",
      name: "Nombre",
      email: "Email",
      password: "Contraseña",
      passwordHint: "Mínimo 8 caracteres.",
      submit: "Crear cuenta",
      hasAccount: "¿Ya tienes cuenta?",
      signIn: "Inicia sesión",
      welcome: "¡Te damos la bienvenida a Planify!",
    },
    logout: "Cerrar sesión",
    sessionClosed: "Has cerrado la sesión.",
  },
  nav: {
    home: "Inicio",
    favorites: "Favoritos",
    recent: "Recientes",
    archived: "Archivados",
    profile: "Perfil",
    comingSoon: "Disponible en la próxima fase",
    userMenu: "Cuenta",
  },
  roles: {
    OWNER: "Propietario",
    EDITOR: "Editor",
    VIEWER: "Lector",
  },
  projects: {
    title: "Proyectos",
    greeting: (name: string) => `Hola, ${name}`,
    newProject: "Nuevo proyecto",
    emptyTitle: "Todavía no tienes proyectos",
    emptyDescription:
      "Crea tu primer proyecto para empezar a planificar tus ideas.",
    loadMore: "Cargar más",
    documents: (count: number) =>
      count === 1 ? "1 documento" : `${count} documentos`,
    members: (count: number) =>
      count === 1 ? "1 miembro" : `${count} miembros`,
    archivedBadge: "Archivado",
    created: "Proyecto creado.",
    updated: "Cambios guardados.",
    archived: "Proyecto archivado.",
    unarchived: "Proyecto desarchivado.",
    deleted: "Proyecto eliminado.",
    actions: {
      edit: "Editar",
      archive: "Archivar",
      unarchive: "Desarchivar",
      delete: "Eliminar",
      favorite: "Favorito",
    },
    form: {
      createTitle: "Nuevo proyecto",
      editTitle: "Editar proyecto",
      name: "Nombre",
      namePlaceholder: "Nombre del proyecto",
      description: "Descripción (opcional)",
      descriptionPlaceholder: "¿De qué va este proyecto?",
      folder: "Carpeta",
      noFolder: "Sin carpeta",
      folderHintOwner: "Solo el propietario puede mover el proyecto.",
      tags: "Etiquetas",
      noTags:
        "Aún no tienes etiquetas. Puedes crearlas desde la barra lateral.",
      create: "Crear proyecto",
      save: "Guardar cambios",
    },
    archiveDialog: {
      title: "Archivar proyecto",
      description: (name: string) =>
        `«${name}» dejará de aparecer en las vistas activas. Podrás desarchivarlo cuando quieras.`,
      confirm: "Archivar",
    },
    deleteDialog: {
      title: "Eliminar proyecto",
      description: (name: string) =>
        `Se eliminará «${name}» junto con sus documentos y comentarios. Esta acción no se puede deshacer.`,
      confirm: "Eliminar definitivamente",
    },
  },
  views: {
    favoritesTitle: "Favoritos",
    favoritesEmpty: "Todavía no has marcado ningún proyecto como favorito.",
    favoritesEmptyDescription:
      "Pulsa la estrella de un proyecto para verlo aquí.",
    recentTitle: "Recientes",
    recentEmpty: "Todavía no has abierto ningún proyecto.",
    recentEmptyDescription: "Los últimos proyectos que abras aparecerán aquí.",
    archivedTitle: "Archivados",
    archivedEmpty: "No tienes proyectos archivados.",
    archivedEmptyDescription:
      "Cuando archives un proyecto, lo encontrarás aquí.",
    folderEmpty: "Esta carpeta está vacía.",
    folderEmptyDescription:
      "Mueve algún proyecto a esta carpeta desde su menú de acciones.",
    tagEmpty: "No hay proyectos con esta etiqueta.",
    tagEmptyDescription:
      "Asigna esta etiqueta desde el menú de acciones de un proyecto.",
  },
  folders: {
    title: "Carpetas",
    new: "Nueva carpeta",
    name: "Nombre de la carpeta",
    create: "Crear carpeta",
    rename: "Renombrar carpeta",
    delete: "Eliminar carpeta",
    deleteDescription: (name: string) =>
      `Los proyectos de «${name}» no se borran: solo dejarán de estar en la carpeta.`,
    empty: "Sin carpetas",
    created: "Carpeta creada.",
    renamed: "Carpeta renombrada.",
    deleted: "Carpeta eliminada.",
  },
  tags: {
    title: "Etiquetas",
    new: "Nueva etiqueta",
    name: "Nombre de la etiqueta",
    create: "Crear etiqueta",
    rename: "Renombrar etiqueta",
    delete: "Eliminar etiqueta",
    deleteDescription: (name: string) =>
      `Se quitará «${name}» de todos los proyectos. Los proyectos no se borran.`,
    empty: "Sin etiquetas",
    created: "Etiqueta creada.",
    renamed: "Etiqueta renombrada.",
    deleted: "Etiqueta eliminada.",
  },
  documents: {
    title: "Documentos",
    newDocument: "Nuevo documento",
    newNote: "Nueva nota",
    newDiagram: "Nuevo diagrama",
    note: "Nota",
    diagram: "Diagrama",
    defaultNoteTitle: "Nota sin título",
    defaultDiagramTitle: "Diagrama sin título",
    empty: "Todavía no hay documentos en este proyecto",
    emptyDescription: "Crea una nota para escribir o un diagrama para dibujar.",
    createdNote: "Nota creada.",
    createdDiagram: "Diagrama creado.",
    renamed: "Documento renombrado.",
    deleted: "Documento eliminado.",
    rename: "Renombrar documento",
    renameLabel: "Título",
    renameHint: "Pulsa para renombrar",
    author: (name: string | null) => name ?? "Usuario eliminado",
    deleteDialog: {
      title: "Eliminar documento",
      description: (name: string) =>
        `Se eliminará «${name}» junto con sus comentarios. Esta acción no se puede deshacer.`,
      confirm: "Eliminar documento",
    },
    placeholderNoteTitle: "El editor de notas llega en la siguiente fase",
    placeholderNoteDescription:
      "Aquí podrás escribir con formato, checklists, imágenes y enlaces (fase 1.3 del roadmap).",
    placeholderDiagramTitle:
      "El editor de diagramas llega en la siguiente fase",
    placeholderDiagramDescription:
      "Aquí tendrás la pizarra estilo Excalidraw con autoguardado (fase 1.4 del roadmap).",
    archivedNotice:
      "Este proyecto está archivado: los documentos son de solo lectura hasta desarchivarlo.",
  },
  editor: {
    placeholder: "Escribe algo…",
    saved: "Guardado",
    dirty: "Cambios sin guardar",
    saving: "Guardando…",
    saveError: "No se pudo guardar.",
    retry: "Reintentar",
    readOnly: "Solo lectura",
    conflictStatus: "Conflicto sin resolver",
    conflictTitle: "Conflicto de edición",
    conflictDescription:
      "Otra persona guardó cambios en este documento mientras lo editabas.",
    conflictReload: "Recargar (descarta lo local)",
    conflictOverwrite: "Sobrescribir (conserva lo local)",
    uploadingImage: "Subiendo imagen…",
    uploadingAttachment: "Subiendo archivo…",
    uploaded: "Subido.",
    loadingPreview: "Obteniendo vista previa…",
    previewFailed: "No se pudo obtener la vista previa; se insertó el enlace.",
    toolbar: {
      h1: "Título 1",
      h2: "Título 2",
      h3: "Título 3",
      bold: "Negrita",
      italic: "Cursiva",
      underline: "Subrayado",
      strike: "Tachado",
      bulletList: "Lista con viñetas",
      orderedList: "Lista numerada",
      taskList: "Lista de tareas",
      quote: "Cita",
      hr: "Separador",
      link: "Enlace",
      linkUrl: "Dirección (URL)",
      linkInsert: "Insertar enlace",
      linkRemove: "Quitar enlace",
      image: "Imagen",
      attachment: "Adjunto",
      imageWidth: "Ancho",
      undo: "Deshacer",
      redo: "Rehacer",
    },
  },
  diagram: {
    loading: "Cargando el diagrama…",
  },
  search: {
    title: "Buscar",
    subtitle: "Proyectos, notas, diagramas, etiquetas y carpetas.",
    open: "Buscar…",
    placeholder: "Buscar en Planify…",
    clear: "Limpiar búsqueda",
    minChars: "Escribe al menos 2 caracteres.",
    promptTitle: "Busca en todo Planify",
    promptDescription:
      "Encuentra proyectos, notas, diagramas, etiquetas y carpetas por nombre o contenido. La búsqueda ignora acentos y mayúsculas.",
    searching: "Buscando…",
    error: "No se pudo buscar. Inténtalo de nuevo.",
    retry: "Reintentar",
    noResults: (query: string) => `Sin resultados para «${query}».`,
    noResultsHint: "Prueba con otras palabras o cambia los filtros.",
    resultsCount: (count: number) =>
      count === 1 ? "1 resultado" : `${count} resultados`,
    projectCount: (count: number) =>
      count === 1 ? "1 proyecto" : `${count} proyectos`,
    groups: {
      projects: "Proyectos",
      notes: "Notas",
      diagrams: "Diagramas",
      tags: "Etiquetas",
      folders: "Carpetas",
    },
    itemKinds: {
      project: "Proyecto",
      note: "Nota",
      diagram: "Diagrama",
      tag: "Etiqueta",
      folder: "Carpeta",
    },
    filters: {
      type: "Tipo",
      status: "Estado",
      folder: "Carpeta",
      tag: "Etiqueta",
      allTypes: "Todos los tipos",
      allStatuses: "Todos los estados",
      allFolders: "Todas las carpetas",
      allTags: "Todas las etiquetas",
      project: "Proyectos",
      note: "Notas",
      diagram: "Diagramas",
      active: "Activos",
      archived: "Archivados",
    },
  },
  sharing: {
    title: "Compartir",
    settingsTitle: "Configuración",
    settingsSubtitle: "Miembros, invitaciones y zona peligrosa del proyecto.",
    backToProject: "Volver al proyecto",
    tabs: {
      members: "Miembros",
      invitations: "Invitaciones",
      danger: "Zona peligrosa",
    },
    readOnlyNotice:
      "Solo el propietario puede gestionar miembros e invitaciones.",
    members: {
      title: "Miembros del proyecto",
      you: "Tú",
      joined: (date: string) => `Se unió ${date}`,
      addTitle: "Agregar por email",
      email: "Email",
      emailPlaceholder: "persona@ejemplo.com",
      role: "Rol",
      submit: "Agregar miembro",
      added: (name: string) => `${name} se ha unido al proyecto.`,
      invitationCreated:
        "Ese email no tiene cuenta todavía. Comparte este enlace de invitación:",
      roleUpdated: "Rol actualizado.",
      removed: "Miembro quitado.",
      changeRole: "Cambiar rol",
      removeTitle: "Quitar miembro",
      removeDescription: (name: string) =>
        `${name} perderá el acceso al proyecto. Sus documentos y comentarios se conservan.`,
      removeConfirm: "Quitar miembro",
    },
    invitations: {
      title: "Invitaciones por enlace",
      description:
        "Enlaces de un solo uso: elige rol y caducidad, y compártelo por donde prefieras.",
      role: "Rol",
      expiry: "Caducidad",
      days: (days: number) => (days === 1 ? "1 día" : `${days} días`),
      create: "Crear enlace",
      created: "Enlace creado y copiado al portapapeles.",
      copy: "Copiar enlace",
      copied: "Enlace copiado al portapapeles.",
      revoke: "Revocar",
      revoked: "Invitación revocada.",
      regenerate: "Regenerar",
      regenerated: "Enlace regenerado: el anterior ya no vale.",
      pending: "Pendientes",
      history: "Historial",
      empty: "No hay invitaciones pendientes",
      emptyDescription:
        "Crea un enlace y envíalo por WhatsApp, email personal o donde prefieras.",
      status: {
        pending: "Pendiente",
        used: "Usada",
        revoked: "Revocada",
        expired: "Caducada",
      },
      expires: (date: string) => `Caduca ${date}`,
      createdAt: (date: string) => `Creada ${date}`,
      link: "Enlace",
    },
    danger: {
      title: "Zona peligrosa",
      description:
        "Archivar congela el proyecto (solo lectura) y eliminar lo borra todo de forma definitiva.",
      archive: "Archivar proyecto",
      unarchive: "Desarchivar proyecto",
      delete: "Eliminar proyecto",
    },
    invite: {
      title: "Invitación",
      toProject: (name: string) => `Te han invitado a «${name}».`,
      roleLabel: (role: string) => `Entrarás como ${role}.`,
      expires: (date: string) => `La invitación caduca ${date}.`,
      accept: "Unirme al proyecto",
      accepted: "¡Te has unido al proyecto!",
      alreadyMember: "Ya eres miembro de este proyecto.",
      goToProject: "Ir al proyecto",
      loginToJoin: "Inicia sesión para unirte",
      registerToJoin: "Crear cuenta para unirme",
      invalidTitle: "Invitación no válida",
      invalid: "Este enlace de invitación no existe.",
      expired: "Esta invitación ha caducado. Pide una nueva al propietario.",
      used: "Esta invitación ya se usó. Pide una nueva al propietario.",
      revoked: "Esta invitación fue revocada por el propietario.",
      home: "Ir al inicio",
      members: (count: number) =>
        count === 1 ? "1 miembro" : `${count} miembros`,
    },
  },
} as const;
